version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo Docker image name $IMAGE_REPO_NAME:$IMAGE_TAG
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker image ls
  post_build:
    commands:
      - echo Build completed on `date`
